# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
  displayName: 'npm install angular cli'

- script: dotnet build
  displayName: 'Build MaxOrg'
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure para estudiantes(2f221f4a-0c67-4193-bdc6-8c67c4e2e3f3)'
    appType: 'webApp'
    appName: 'maxorg'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'